# Generated by Django 3.2.12 on 2022-04-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0003_tokenproxy'),
        ('app', '0003_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myuser',
        ),
    ]
